# System Information to README.md Script
# Collects computer info, Windows version, and storage status

# Get computer information
$computerInfo = Get-ComputerInfo

# Get Windows version details
$windowsVersion = "$($computerInfo.WindowsProductName) - Version $($computerInfo.WindowsVersion) (Build $($computerInfo.OsBuildNumber))"

# Get storage information for all drives
$drives = Get-PSDrive -PSProvider FileSystem | Where-Object { $_.Used -ne $null }

# Start building the README content
$readmeContent = @"
# System Information Report
Generated on: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

---

## Computer Information

**Computer Name:** $($computerInfo.CsName)
**Manufacturer:** $($computerInfo.CsManufacturer)
**Model:** $($computerInfo.CsModel)
**Processor:** $($computerInfo.CsProcessors.Name)
**Total Physical Memory:** $([math]::Round($computerInfo.CsTotalPhysicalMemory / 1GB, 2)) GB
**OS Architecture:** $($computerInfo.OsArchitecture)

---

## Windows Version

$windowsVersion

**OS Install Date:** $($computerInfo.OsInstallDate)
**Last Boot Time:** $($computerInfo.OsLastBootUpTime)

---

## Storage Status

"@
# Add storage information for each drive
foreach ($drive in $drives) {
    $usedGB = [math]::Round($drive.Used / 1GB, 2)
    $freeGB = [math]::Round($drive.Free / 1GB, 2)
    $totalGB = $usedGB + $freeGB
    $usedBytes = $drive.Used
    $freeBytes = $drive.Free
    $usedPercent = [math]::Round(($drive.Used / ($drive.Used + $drive.Free)) * 100, 2)
    
    $readmeContent += @"

### Drive $($drive.Name):
- **Used:** $usedGB GB ($usedBytes bytes) - $usedPercent%
- **Free:** $freeGB GB ($freeBytes bytes)
- **Total:** $totalGB GB

"@
}

# Add footer
$readmeContent += @"

---

*This report was automatically generated by the System Information Script*
"@

# Write to README.md
$readmeContent | Out-File -FilePath "README.md" -Encoding UTF8

Write-Host "README.md has been created successfully!" -ForegroundColor Green
Write-Host "Location: $(Get-Location)\README.md" -ForegroundColor Cyan

Write-Host "Contents Added: `n$readmeContent"